// src/components/FreezeNotice.jsx
// Automated legal freeze notice generator with PDF download

import { useState } from 'react'
import { motion } from 'framer-motion'
import { FileText, Download, Copy, Printer, CheckCheck, Lock } from 'lucide-react'
import { jsPDF } from 'jspdf'

function buildNoticeText({ caseData, officer, authority, victimRef, additionalNotes }) {
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const timeStr = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
  const trace = caseData.trace_result || {}
  const risk  = caseData.risk_assessment || {}
  const ml    = caseData.ml_analysis || {}
  const cc    = caseData.cross_chain_analysis || {}
  const exchange = trace.attribution?.exchange || 'Unknown Exchange'

  return `
OFFICIAL NOTICE — CRYPTOCURRENCY ASSET PRESERVATION REQUEST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REFERENCE NO.:    ${caseData.case_id}
DATE & TIME:      ${dateStr} at ${timeStr} IST
ISSUING AUTHORITY: ${authority || 'Cyber Crime Cell, India'}
OFFICER IN CHARGE: ${officer || caseData.reporting_officer || 'Not specified'}
VICTIM REF.:      ${victimRef || 'Confidential'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO:  Compliance & Legal Team
     ${exchange}

SUBJECT: URGENT REQUEST FOR ASSET FREEZE AND ACCOUNT PRESERVATION

Dear Sir/Madam,

This notice is issued pursuant to the powers vested under the Information
Technology Act, 2000 and the Prevention of Money Laundering Act, 2002 (PMLA)
in connection with a reported cryptocurrency fraud investigation.

1. SUBJECT WALLET ADDRESS
   ─────────────────────────────────────────────
   Address:   ${caseData.victim_reported_address}
   Chain:     ${(caseData.chain || 'ethereum').toUpperCase()}
   Fraud Category: ${caseData.complaint_category || 'Not specified'}

2. RISK ASSESSMENT SUMMARY
   ─────────────────────────────────────────────
   Risk Score:  ${risk.risk_score || 'N/A'} / 100
   Risk Band:   ${risk.risk_band || 'N/A'}
   
   Risk Indicators:
   ${(risk.reasons || []).map(r => `   • ${r}`).join('\n') || '   None identified'}

3. AI/ML FRAUD ANALYSIS
   ─────────────────────────────────────────────
   Fraud Typology:        ${ml.top_fraud_typology || 'N/A'}
   Classifier Confidence: ${(ml.typology_confidence || 0).toFixed(1)}%
   Anomaly Score:         ${(ml.anomaly_score || 0).toFixed(1)} / 100 (${ml.anomaly_band || 'N/A'})
   
   Patterns Detected:
   ${(ml.patterns_detected || []).map(p => `   • ${p.pattern_name} (risk boost: +${p.risk_boost})`).join('\n') || '   None'}

4. BLOCKCHAIN TRACE FINDINGS
   ─────────────────────────────────────────────
   Hops Traced:          ${trace.traced_hops || 'N/A'}
   Attribution Exchange: ${exchange}
   Data Source:          ${trace.data_source === 'live' ? 'Live Blockchain Data' : 'Simulation Fallback'}
   Cross-Chain Detected: ${trace.flags?.cross_chain_detected ? 'YES — Multi-chain tracing required' : 'No'}

${cc.bridge_events_detected > 0 ? `5. CROSS-CHAIN BRIDGE ALERT
   ─────────────────────────────────────────────
   Bridge Events Detected: ${cc.bridge_events_detected}
   Cross-Chain Risk:        ${cc.cross_chain_risk}
   Summary: ${cc.summary}
   
   Bridges Used:
   ${(cc.bridge_hops || []).map(b => `   • ${b.bridge_name}: ${b.bridge_contract}`).join('\n')}

` : ''}
6. REQUESTED ACTIONS
   ─────────────────────────────────────────────
   You are hereby directed to:
   
   a) IMMEDIATELY FREEZE all assets held in the wallet address(es) cited above
      and any associated deposit accounts linked to the suspect wallet.
   
   b) PRESERVE all transaction records, KYC documents, IP logs, device
      fingerprints, and communications related to the above account(s).
   
   c) PROVIDE a complete transaction history for the above wallet(s) covering
      the last 365 days, or since account creation, whichever is earlier.
   
   d) DO NOT ALERT the account holder(s) about this notice or any consequent
      action taken by your platform.
   
   e) RESPOND to this notice within 72 hours via official law enforcement
      channels or the designated MLAT contact for your jurisdiction.

${additionalNotes ? `7. ADDITIONAL NOTES
   ─────────────────────────────────────────────
   ${additionalNotes}

` : ''}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NON-COMPLIANCE with this notice may result in legal proceedings under
applicable cybercrime and anti-money-laundering legislation.

Authorized by:
${officer || 'Investigating Officer'}
${authority || 'Cyber Crime Cell'}
CRYPTOTRACE — Fraud Attribution System (v2.0)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUTO-GENERATED BY NCRP/SAHYOG FRAUD ATTRIBUTION SYSTEM
Case Reference: ${caseData.case_id} | Generated: ${now.toISOString()}
This is a machine-generated document. Officer verification required before legal action.
`.trim()
}

export default function FreezeNotice({ caseData }) {
  const [officer, setOfficer] = useState(caseData?.reporting_officer || '')
  const [authority, setAuthority] = useState('Cyber Crime Cell, India')
  const [victimRef, setVictimRef] = useState('')
  const [additionalNotes, setAdditionalNotes] = useState('')
  const [copied, setCopied] = useState(false)
  const [generated, setGenerated] = useState(false)

  if (!caseData) return null

  const noticeText = buildNoticeText({ caseData, officer, authority, victimRef, additionalNotes })

  function handleCopy() {
    navigator.clipboard.writeText(noticeText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  function handleDownloadPDF() {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })
    const margin = 50
    const pageWidth = doc.internal.pageSize.getWidth()
    const usableWidth = pageWidth - 2 * margin
    const lines = doc.splitTextToSize(noticeText, usableWidth)
    const lineHeight = 11
    let y = margin

    doc.setFont('Courier', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(20, 20, 20)

    lines.forEach(line => {
      if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(line, margin, y)
      y += lineHeight
    })

    doc.save(`FREEZE-NOTICE-${caseData.case_id}.pdf`)
    setGenerated(true)
  }

  function handlePrint() {
    const win = window.open('', '_blank')
    win.document.write(`<html><head><title>Freeze Notice — ${caseData.case_id}</title>
    <style>body{font-family:'Courier New',monospace;font-size:10pt;padding:40px;line-height:1.6;color:#000;}pre{white-space:pre-wrap;word-wrap:break-word;}</style>
    </head><body><pre>${noticeText}</pre></body></html>`)
    win.document.close()
    win.print()
  }

  const inputCls = 'bg-zinc-50 border border-zinc-300 text-black placeholder-zinc-400 font-mono text-xs px-3 py-2 rounded-md focus:outline-none focus:border-black transition-colors w-full'

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white border border-zinc-200 rounded-lg p-5 font-sans shadow-sm"
    >
      <div className="flex items-center gap-2 pb-3 mb-4 border-b border-zinc-200">
        <Lock size={15} className="text-black" />
        <h3 className="text-xs font-semibold uppercase tracking-wider text-black">
          Automated Freeze Notice Generator
        </h3>
      </div>

      {/* Form fields */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
        <div>
          <label className="text-[11px] font-mono text-zinc-700 mb-1 block font-semibold">INVESTIGATING OFFICER</label>
          <input className={inputCls} value={officer} onChange={e => setOfficer(e.target.value)} placeholder="Insp. Name / Badge No." />
        </div>
        <div>
          <label className="text-[11px] font-mono text-zinc-700 mb-1 block font-semibold">ISSUING AUTHORITY</label>
          <input className={inputCls} value={authority} onChange={e => setAuthority(e.target.value)} placeholder="Cyber Crime Cell, India" />
        </div>
        <div>
          <label className="text-[11px] font-mono text-zinc-700 mb-1 block font-semibold">VICTIM REFERENCE (MASKED)</label>
          <input className={inputCls} value={victimRef} onChange={e => setVictimRef(e.target.value)} placeholder="VIC-2026-XXXX" />
        </div>
        <div>
          <label className="text-[11px] font-mono text-zinc-700 mb-1 block font-semibold">ADDITIONAL STATUTORY NOTES</label>
          <input className={inputCls} value={additionalNotes} onChange={e => setAdditionalNotes(e.target.value)} placeholder="Special preservation directives..." />
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex flex-wrap items-center gap-2 mb-4">
        <button
          onClick={handleDownloadPDF}
          className="flex items-center gap-2 bg-black text-white font-semibold text-xs px-4 py-2 rounded-md hover:bg-zinc-800 transition-all shadow-xs"
        >
          <Download size={13} />
          Download PDF Notice
        </button>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 border border-zinc-300 bg-zinc-100 text-black font-semibold text-xs px-3.5 py-2 rounded-md hover:bg-zinc-200 transition-colors shadow-2xs"
        >
          {copied ? <CheckCheck size={13} className="text-black" /> : <Copy size={13} />}
          {copied ? 'Copied' : 'Copy Text'}
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 border border-zinc-300 bg-zinc-100 text-black font-semibold text-xs px-3.5 py-2 rounded-md hover:bg-zinc-200 transition-colors shadow-2xs"
        >
          <Printer size={13} />
          Print
        </button>
      </div>

      {generated && (
        <div className="mb-3 text-xs text-black font-mono flex items-center gap-1.5 bg-zinc-100 border border-black px-3 py-1.5 rounded-md font-semibold">
          <CheckCheck size={13} className="text-black" /> PDF generated and saved as FREEZE-NOTICE-{caseData.case_id}.pdf
        </div>
      )}

      {/* Notice preview */}
      <div className="relative mt-2">
        <div className="flex items-center gap-2 mb-2">
          <FileText size={13} className="text-zinc-600" />
          <span className="text-xs font-mono text-zinc-700 uppercase font-semibold">Legal Notice Document Preview</span>
        </div>
        <pre className="bg-zinc-50 border border-zinc-300 rounded-md p-4 text-[11px] font-mono text-black overflow-auto max-h-72 leading-relaxed whitespace-pre-wrap selection:bg-zinc-200 shadow-2xs">
          {noticeText}
        </pre>
      </div>
    </motion.div>
  )
}
