// src/components/ReportPanel.jsx
// Comprehensive Forensic Investigation Report Generator
// Minimalist Black & White aesthetic matching CRYPTOTRACE design system

import { useState } from 'react'
import { motion } from 'framer-motion'
import { FileText, Download, Copy, Printer, CheckCheck, ShieldCheck, ArrowDownToLine, ExternalLink, AlertTriangle } from 'lucide-react'
import { jsPDF } from 'jspdf'

export default function ReportPanel({ caseData, report }) {
  const [copied, setCopied] = useState(false)
  const [downloadingPdf, setDownloadingPdf] = useState(false)

  if (!caseData) return null

  const trace = caseData.trace_result || {}
  const risk  = caseData.risk_assessment || {}
  const ml    = caseData.ml_analysis || {}
  const cc    = caseData.cross_chain_analysis || {}
  const rpt   = report || {}

  const caseId = caseData.case_id || 'UNKNOWN'
  const reportId = rpt.report_id || `RPT-${caseId}`
  const timestamp = rpt.generated_at ? new Date(rpt.generated_at * 1000).toLocaleString('en-IN') : new Date().toLocaleString('en-IN')
  const attribution = trace.attribution?.exchange || (typeof rpt.attribution_finding === 'string' ? rpt.attribution_finding : 'NOT RESOLVED')
  const riskScore = risk.risk_score ?? rpt.risk_score ?? 0
  const riskBand = risk.risk_band || rpt.risk_band || 'LOW'

  // Build clean text representation
  const textSummary = `
================================================================================
CRYPTOTRACE — CRYPTOCURRENCY FRAUD ATTRIBUTION REPORT
NATIONAL CYBER FRAUD COORDINATION & INVESTIGATION DOSSIER
================================================================================

REPORT IDENTIFIER:    ${reportId}
CASE REFERENCE:       ${caseId}
DATE & TIME:          ${timestamp}
SECURITY LEVEL:       LAW ENFORCEMENT SENSITIVE // OFFICIAL FORENSIC LEAD
TARGET WALLET:        ${caseData.victim_reported_address}
BLOCKCHAIN NETWORK:   ${(caseData.chain || 'ethereum').toUpperCase()}
FRAUD CLASSIFICATION: ${caseData.complaint_category || 'Unclassified'}
INVESTIGATING OFFICER:${caseData.reporting_officer || 'Cyber Forensics Division'}

--------------------------------------------------------------------------------
1. RISK ASSESSMENT & ENTITY ATTRIBUTION
--------------------------------------------------------------------------------
Attribution Finding:  ${attribution}
Overall Risk Score:   ${riskScore} / 100 (${riskBand})
Trace Depth Traced:   ${trace.traced_hops || rpt.hops_traced || 0} Hops
Key Risk Flags:
${(risk.reasons || rpt.risk_reasons || []).map(r => `  • ${r}`).join('\n') || '  • No critical anomalies recorded'}

--------------------------------------------------------------------------------
2. AI/ML FORENSIC CLASSIFICATION
--------------------------------------------------------------------------------
Top Fraud Typology:   ${ml.top_fraud_typology || rpt.ml_fraud_typology || 'N/A'}
Classification Conf.: ${(ml.typology_confidence || rpt.ml_typology_confidence || 0).toFixed(1)}%
Anomaly Score:        ${(ml.anomaly_score || rpt.ml_anomaly_score || 0).toFixed(1)} / 100
Anomaly Band:         ${ml.anomaly_band || rpt.ml_anomaly_band || 'TYPICAL'}
Detected Patterns:    ${(ml.patterns_detected?.map(p => p.pattern_name) || rpt.ml_patterns_detected || []).join(', ') || 'Standard direct transaction flow'}
ML Recommendation:    ${ml.investigative_recommendation || rpt.ml_recommendation || 'Proceed with standard entity subpoenas'}

--------------------------------------------------------------------------------
3. CROSS-CHAIN & DEFI ATTRIBUTION
--------------------------------------------------------------------------------
Bridge Events:        ${cc.bridge_events_detected ?? rpt.cross_chain_bridges_detected ?? 0}
DeFi Events:          ${cc.defi_events_detected ?? rpt.cross_chain_defi_detected ?? 0}
Cross-Chain Risk:     ${cc.cross_chain_risk || rpt.cross_chain_risk || 'LOW'}
Summary:              ${cc.summary || rpt.cross_chain_summary || 'No cross-chain bridge or DeFi conversion detected'}

--------------------------------------------------------------------------------
4. STATUTORY RECOMMENDED ACTION
--------------------------------------------------------------------------------
${rpt.recommended_action || 'Issue formal preservation request to exchange compliance officer. Subpoena KYC/CDD documentation.'}

--------------------------------------------------------------------------------
DISCLAIMER
Auto-generated investigative lead generated by CRYPTOTRACE v2.0 engine.
Requires authorized officer verification prior to statutory enforcement.
================================================================================
`.trim()

  function handleCopy() {
    navigator.clipboard.writeText(textSummary).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  function handleDownloadJSON() {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(rpt.report_id ? rpt : caseData, null, 2))
    const dlAnchor = document.createElement('a')
    dlAnchor.setAttribute("href", dataStr)
    dlAnchor.setAttribute("download", `${reportId}.json`)
    dlAnchor.click()
  }

  function handleDownloadPDF() {
    setDownloadingPdf(true)
    try {
      const doc = new jsPDF({ unit: 'pt', format: 'a4' })
      const margin = 45
      const pageWidth = doc.internal.pageSize.getWidth()
      const usableWidth = pageWidth - 2 * margin
      const lines = doc.splitTextToSize(textSummary, usableWidth)
      const lineHeight = 11.5
      let y = margin

      doc.setFont('Courier', 'normal')
      doc.setFontSize(8.5)
      doc.setTextColor(20, 20, 20)

      lines.forEach(line => {
        if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage()
          y = margin
        }
        doc.text(line, margin, y)
        y += lineHeight
      })

      doc.save(`${reportId}_Cryptotrace_Forensics.pdf`)
    } finally {
      setDownloadingPdf(false)
    }
  }

  function handlePrint() {
    window.print()
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className="space-y-6"
    >
      {/* Action bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-zinc-50 border border-zinc-200 p-4 rounded-xl">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-black text-white flex items-center justify-center">
            <FileText size={18} />
          </div>
          <div>
            <h3 className="text-sm font-bold text-black font-mono">
              Investigation Report — {reportId}
            </h3>
            <p className="text-[11px] text-zinc-500 font-mono">
              Official forensic lead generated for NCRP / LEA investigative proceedings
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadPDF}
            disabled={downloadingPdf}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-black text-white rounded-lg hover:bg-zinc-800 transition-colors shadow-xs font-mono"
            title="Download formatted PDF report"
          >
            <Download size={13} />
            <span>{downloadingPdf ? 'Exporting...' : 'Download PDF'}</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-zinc-300 text-zinc-800 rounded-lg hover:bg-zinc-100 hover:text-black transition-colors shadow-2xs font-mono"
            title="Download raw JSON data"
          >
            <ArrowDownToLine size={13} />
            <span>Export JSON</span>
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-zinc-300 text-zinc-800 rounded-lg hover:bg-zinc-100 hover:text-black transition-colors shadow-2xs font-mono"
            title="Copy plaintext report"
          >
            {copied ? <CheckCheck size={13} className="text-emerald-600" /> : <Copy size={13} />}
            <span>{copied ? 'Copied' : 'Copy'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-zinc-300 text-zinc-800 rounded-lg hover:bg-zinc-100 hover:text-black transition-colors shadow-2xs font-mono"
            title="Print report"
          >
            <Printer size={13} />
            <span>Print</span>
          </button>
        </div>
      </div>

      {/* Styled Report Dossier */}
      <div className="bg-white border border-zinc-300 rounded-xl p-6 sm:p-8 shadow-sm space-y-6 font-mono text-xs text-zinc-800">
        
        {/* Header dossier */}
        <div className="border-b-2 border-black pb-5">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="text-lg font-black tracking-tight text-black flex items-center gap-2">
                <ShieldCheck size={20} className="text-black" />
                <span>CRYPTOTRACE FORENSIC DOSSIER</span>
              </div>
              <div className="text-[11px] text-zinc-600 mt-0.5">
                Standardised Law Enforcement Investigation Report (v2.0)
              </div>
            </div>
            <div className="sm:text-right font-mono text-[11px] space-y-0.5 text-zinc-600">
              <div><span className="font-bold text-black">DOSSIER NO:</span> {reportId}</div>
              <div><span className="font-bold text-black">TIMESTAMP:</span> {timestamp}</div>
              <div><span className="font-bold text-black">CASE REF:</span> {caseId}</div>
            </div>
          </div>
        </div>

        {/* Section 1: Subject Target Profile */}
        <div>
          <div className="text-xs font-bold uppercase tracking-wider text-black bg-zinc-100 px-3 py-1.5 rounded mb-3 border border-zinc-200">
            1. Target Subject Wallet Profile
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 px-1">
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Suspect Address</span>
              <span className="font-bold text-black break-all text-[11.5px]">{caseData.victim_reported_address}</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Chain & Category</span>
              <span className="font-bold text-black">{(caseData.chain || 'ethereum').toUpperCase()} — {caseData.complaint_category}</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Reporting Officer</span>
              <span className="font-bold text-black">{caseData.reporting_officer || 'Cyber Crime Division (NCRP)'}</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Data Pipeline</span>
              <span className="font-bold text-black">{trace.data_source === 'live' ? 'Live On-Chain RPC Engine' : 'Deterministic Simulation'}</span>
            </div>
          </div>
        </div>

        {/* Section 2: Attribution & Risk Evaluation */}
        <div>
          <div className="text-xs font-bold uppercase tracking-wider text-black bg-zinc-100 px-3 py-1.5 rounded mb-3 border border-zinc-200">
            2. VASP Attribution & Risk Assessment
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 px-1">
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg sm:col-span-2">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Identified Exchange / VASP</span>
              <span className="font-bold text-black text-sm">{attribution}</span>
              <span className="text-[10.5px] text-zinc-500 block mt-1">Traced across {trace.traced_hops || 0} transaction hops</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Risk Assessment</span>
              <div className="flex items-baseline gap-2 mt-0.5">
                <span className="text-lg font-black text-black">{riskScore}/100</span>
                <span className="font-bold px-1.5 py-0.5 text-[10px] bg-black text-white rounded">{riskBand}</span>
              </div>
            </div>
          </div>

          {risk.reasons?.length > 0 && (
            <div className="mt-3 bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium mb-1.5">Identified Risk Flags</span>
              <ul className="space-y-1">
                {risk.reasons.map((r, i) => (
                  <li key={i} className="flex items-center gap-2 text-[11px] text-zinc-800">
                    <span className="w-1.5 h-1.5 rounded-full bg-black shrink-0" />
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Section 3: AI/ML Typology Classification */}
        <div>
          <div className="text-xs font-bold uppercase tracking-wider text-black bg-zinc-100 px-3 py-1.5 rounded mb-3 border border-zinc-200">
            3. Artificial Intelligence & Forensic Typology
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 px-1">
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Primary Typology</span>
              <span className="font-bold text-black text-sm">{ml.top_fraud_typology || 'Phishing / Scam'}</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Confidence Score</span>
              <span className="font-bold text-black text-sm">{(ml.typology_confidence || 0).toFixed(1)}%</span>
            </div>
            <div className="bg-zinc-50 border border-zinc-200 p-3 rounded-lg">
              <span className="text-[10.5px] text-zinc-500 block uppercase font-medium">Anomaly Rating</span>
              <span className="font-bold text-black text-sm">{(ml.anomaly_score || 0).toFixed(1)} / 100 ({ml.anomaly_band || 'TYPICAL'})</span>
            </div>
          </div>
          {ml.investigative_recommendation && (
            <div className="mt-3 bg-zinc-50 border border-zinc-200 p-3 rounded-lg text-[11px] text-zinc-800 leading-relaxed">
              <span className="font-bold text-black block mb-1">Investigative Recommendation:</span>
              {ml.investigative_recommendation}
            </div>
          )}
        </div>

        {/* Section 4: Statutory Directives */}
        <div>
          <div className="text-xs font-bold uppercase tracking-wider text-black bg-zinc-100 px-3 py-1.5 rounded mb-3 border border-zinc-200">
            4. Recommended Law Enforcement Directives
          </div>
          <div className="bg-zinc-50 border border-zinc-200 p-4 rounded-lg space-y-2 text-[11.5px] leading-relaxed">
            <p className="font-semibold text-black">
              {rpt.recommended_action || 'Issue formal Section 91 CrPC notice to identified exchange compliance officer. Subpoena KYC records, IP access logs, and associated banking rails.'}
            </p>
            <p className="text-zinc-500 text-[10.5px] pt-2 border-t border-zinc-200">
              Disclaimer: Generated automatically by CRYPTOTRACE Fraud Attribution Engine v2.0. Requires officer verification before legal action.
            </p>
          </div>
        </div>

      </div>
    </motion.div>
  )
}
